name: Mirroring

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ID_STEFANO }}
        with:
          source-repo: "git@github.com:stefanobartoletti/bricks.git"
          destination-repo: "git@gitlab.com:stefanobartoletti/bricks.git"

  restart_when_failed:
    name: Restarts the scheduled run when it failed
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && failure()
    needs: [git-mirror]
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/stefanobartoletti/bricks/actions/workflows/9476994/dispatches \
          -d '{"ref": "${{ github.ref }}" }'