name: Mirror

on: [ push ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    if: github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REPO_BRICKS }}
        with:
          source-repo: "git@github.com:stefanobartoletti/bricks.git"
          destination-repo: "git@gitlab.com:stefanobartoletti/bricks.git"